title: Rojana Binte Azad
logo: /assets/img/propic_wifey.jpeg
#description: An individual fascinated by the potential of intelligent machines to explore and explain the complexities of the quantum universe.
email: <a href="mailto:rojanaoyshi0111@gmail.com">rojanaoyshi0111@gmail.com</a>
show_downloads: false
# google_analytics: G-ZLK2GHB055
color-scheme: auto
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

# You can find fonts from https://iconify.design or https://fontawesome.com. Below is just an example illustrating how to use custom icons
sidebar:
  - name: Academics
    link: ./academics.html
  # - name: Teaching
  #   link: ./teaching.html
  - name: Research
    link: ./research.html
  # - name: Seminars
  #   link: ./seminars.html
  # - name: Others
  #   link: ./others.html
  
  - name: Google Scholar
    icon: <svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" role="img" style="vertical-align:-0.125em;" width="1em" height="1em" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24"><path d="M5.242 13.769L0 9.5L12 0l12 9.5l-5.242 4.269C17.548 11.249 14.978 9.5 12 9.5c-2.977 0-5.548 1.748-6.758 4.269zM12 10a7 7 0 1 0 0 14a7 7 0 0 0 0-14z" fill="currentColor"/></svg>
    link: https://scholar.google.com/citations?user=RsHHD8IAAAAJ&hl=en&oi=ao
  # - name: GitHub
  #   icon: <i class="fa-brands fa-github"></i>
  #   link: https://github.com/chacconed
  - name: Linkedin
    icon: <i class="fab fa-linkedin-in"></i>
    link: https://www.linkedin.com/in/rojana-azad-101239214/
    
  - name: Research Gate
    icon: <svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" role="img" style="vertical-align:-0.125em;" width="1em" height="1em" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24"><g fill="none"><path d="m 271 383 c -15 -4 -23 -10 -36 -26 c -9 -12 -26 -39 -35 -53 l -6 -11 h -24 l 0 34 c 1 43 0 42 19 45 l 10 1 l 0 4 l 0 4 h -80 l 0 -4 c 0 -4 1 -4 9 -6 c 10 -2 14 -5 15 -14 c 1 -4 1 -31 1 -79 c 0 -70 -1 -72 -3 -77 c -3 -5 -7 -7 -18 -8 c -4 -1 -5 -1 -5 -5 v -4 l 43 -1 c 55 -1 65 0 81 11 c 15 10 22 24 20 43 c -1 21 -17 42 -37 50 c -4 1 -7 3 -7 3 c 0 2 17 28 28 43 c 15 21 27 32 36 37 c 4 2 9 3 10 3 c 3 0 3 1 3 4 c 0 3 -1 5 -2 5 c -5 2 -19 2 -26 0 Z m -57 -109 c 14 -7 22 -18 23 -35 c 1 -13 -2 -22 -10 -30 c -9 -10 -25 -14 -48 -12 l -10 1 v 39 c 0 36 0 40 2 40 c 1 0 9 1 18 0 c 14 0 17 -1 24 -4 Z" fill="currentColor"/></g></svg>
    link: https://www.researchgate.net/profile/Rojana-Azad
  - name: ''



  # - name: Project Repository
  #   icon: <svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" role="img" style="vertical-align:-0.125em;" width="1em" height="1em" preserveAspectRatio="xMidYMid meet" viewBox="0 0 16 16"><g fill="currentColor"><path d="M12.643 15C13.979 15 15 13.845 15 12.5V5H1v7.5C1 13.845 2.021 15 3.357 15h9.286zM5.5 7h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1 0-1zM.8 1a.8.8 0 0 0-.8.8V3a.8.8 0 0 0 .8.8h14.4A.8.8 0 0 0 16 3V1.8a.8.8 0 0 0-.8-.8H.8z"/></g></svg>
  #   link: https://github.com/BDHU/minimalist

# https://github.com/github/pages-gem/issues/399#issuecomment-301827749
# When running locally, we run into the following error —
# GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
# adding this avoids it
# github: [metadata]
